name: kasir_pro
description: "Aplikasi kasir modern untuk Windows dan Android."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite_common_ffi: ^2.3.3 # Untuk Windows & Desktop
  sqflite: ^2.3.3 # Untuk Android & iOS
  path_provider: ^2.1.3
  path: ^1.9.0

  # UI & Utilities
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  
  # CSV Handling
  csv: ^6.0.0

  # Printer
  esc_pos_utils_plus: ^2.0.4
  flutter_blue_plus: ^1.31.20 # Sesuai permintaan (untuk Bluetooth)
  # Catatan: Untuk USB direct di Windows, mungkin perlu pendekatan lain seperti 'usb_serial'.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/logo/ # Buat folder ini jika Anda ingin menambahkan logo nanti