# Nama workflow yang akan muncul di tab "Actions" di GitHub
name: Build Windows Installer

# Pemicu: Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # Job untuk membuat installer Windows
  build-windows-installer:
    # Menggunakan mesin virtual Windows versi terbaru
    runs-on: windows-latest

    steps:
      # 1. Mengunduh kode dari repository Anda
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Menginstal dan mengatur Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Mengaktifkan dukungan build untuk desktop Windows
      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      # 4. Mengunduh semua paket yang dibutuhkan proyek
      - name: Get dependencies
        run: flutter pub get

      # 5. Membuat build aplikasi Flutter (versi portable)
      - name: Build Flutter application
        run: flutter build windows --release

      # 6. Menginstal Inno Setup
      # --- BAGIAN YANG DIPERBAIKI ---
      - name: Setup Inno Setup
        uses: crazy-max/ghaction-inno-setup@v4.0.0
        with:
          version: "6.2.2"

      # 7. Membuat installer .exe menggunakan Inno Setup
      - name: Compile installer script
        run: iscc "installer_script.iss"

      # 8. Mengunggah file setup.exe sebagai artifact yang bisa diunduh
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: kasir-pro-installer
          path: Output/kasir-pro-setup.exe
